/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jposix_Posix */

#ifndef _Included_jposix_Posix
#define _Included_jposix_Posix
#ifdef __cplusplus
extern "C" {
#endif
#undef jposix_Posix_STDIN_FILENO
#define jposix_Posix_STDIN_FILENO 0L
#undef jposix_Posix_STDOUT_FILENO
#define jposix_Posix_STDOUT_FILENO 1L
#undef jposix_Posix_STDERR_FILENO
#define jposix_Posix_STDERR_FILENO 2L
#undef jposix_Posix_SEEK_SET
#define jposix_Posix_SEEK_SET 0L
#undef jposix_Posix_SEEK_CUR
#define jposix_Posix_SEEK_CUR 1L
#undef jposix_Posix_SEEK_END
#define jposix_Posix_SEEK_END 2L
/*
 * Class:     jposix_Posix
 * Method:    S_ISTYPE
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_jposix_Posix_S_1ISTYPE
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    S_ISDIR
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jposix_Posix_S_1ISDIR
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    S_ISBLK
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jposix_Posix_S_1ISBLK
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    S_ISREG
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jposix_Posix_S_1ISREG
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    S_ISFIFO
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jposix_Posix_S_1ISFIFO
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    S_ISLNK
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jposix_Posix_S_1ISLNK
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    S_ISSOCK
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jposix_Posix_S_1ISSOCK
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    access
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_access
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     jposix_Posix
 * Method:    acct
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_acct
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    alarm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_alarm
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    brk
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_brk
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jposix_Posix
 * Method:    chdir
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_chdir
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    chown
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_chown
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    chroot
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_chroot
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    confstr
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jposix_Posix_confstr
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    creat
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_creat
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     jposix_Posix
 * Method:    crypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jposix_Posix_crypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    ctermid
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jposix_Posix_ctermid
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    daemon
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_daemon
  (JNIEnv *, jclass, jboolean, jboolean);

/*
 * Class:     jposix_Posix
 * Method:    dup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_dup
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    dup2
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_dup2
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    encrypt
 * Signature: ([BZ)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_encrypt
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     jposix_Posix
 * Method:    endusershell
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_endusershell
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    environ
 * Signature: ()[[B
 */
JNIEXPORT jobjectArray JNICALL Java_jposix_Posix_environ
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    euidaccess
 * Signature: ([BI)Z
 */
JNIEXPORT void JNICALL Java_jposix_Posix_euidaccess
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     jposix_Posix
 * Method:    execv
 * Signature: ([B[[B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_execv
  (JNIEnv *, jclass, jbyteArray, jobjectArray);

/*
 * Class:     jposix_Posix
 * Method:    execve
 * Signature: ([B[[B[[B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_execve
  (JNIEnv *, jclass, jbyteArray, jobjectArray, jobjectArray);

/*
 * Class:     jposix_Posix
 * Method:    execvp
 * Signature: ([B[[B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_execvp
  (JNIEnv *, jclass, jbyteArray, jobjectArray);

/*
 * Class:     jposix_Posix
 * Method:    _exit
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix__1exit
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    fchdir
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_fchdir
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    fchown
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_fchown
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    _fcntl1
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1fcntl1
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    _fcntl2
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1fcntl2
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    fdatasync
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_fdatasync
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    fexecve
 * Signature: (I[[B[[B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_fexecve
  (JNIEnv *, jclass, jint, jobjectArray, jobjectArray);

/*
 * Class:     jposix_Posix
 * Method:    fork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_fork
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    fpathconf
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_jposix_Posix_fpathconf
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    fstat
 * Signature: (I)Ljposix/struct/Stat;
 */
JNIEXPORT jobject JNICALL Java_jposix_Posix_fstat
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    fsync
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_fsync
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    ftruncate
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_ftruncate
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     jposix_Posix
 * Method:    getcwd
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jposix_Posix_getcwd
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getdomainname
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jposix_Posix_getdomainname
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getdtablesize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_getdtablesize
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getegid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_getegid
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    geteuid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_geteuid
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getgid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_getgid
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getgroups
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jposix_Posix_getgroups
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    gethostid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_gethostid
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    gethostname
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jposix_Posix_gethostname
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getlogin
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jposix_Posix_getlogin
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getpagesize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_getpagesize
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getpass
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jposix_Posix_getpass
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    getpgid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_getpgid
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    getpid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_getpid
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getppid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_getppid
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getresgid
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jposix_Posix_getresgid
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getresuid
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_jposix_Posix_getresuid
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getsid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_getsid
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    getuid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_getuid
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    getusershell
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_jposix_Posix_getusershell
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    isatty
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jposix_Posix_isatty
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    lchown
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_lchown
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    link
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_link
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    lockf
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_lockf
  (JNIEnv *, jclass, jint, jint, jlong);

/*
 * Class:     jposix_Posix
 * Method:    lseek
 * Signature: (IJI)V
 */
JNIEXPORT jlong JNICALL Java_jposix_Posix_lseek
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     jposix_Posix
 * Method:    lstat
 * Signature: ([B)Ljposix/struct/Stat;
 */
JNIEXPORT jobject JNICALL Java_jposix_Posix_lstat
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    nice
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_nice
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    open
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_open
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_pause
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    pathconf
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_jposix_Posix_pathconf
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     jposix_Posix
 * Method:    pipe
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_pipe
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     jposix_Posix
 * Method:    posix_fadvise
 * Signature: (IJJI)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_posix_1fadvise
  (JNIEnv *, jclass, jint, jlong, jlong, jint);

/*
 * Class:     jposix_Posix
 * Method:    posix_fallocate
 * Signature: (IJJ)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_posix_1fallocate
  (JNIEnv *, jclass, jint, jlong, jlong);

/*
 * Class:     jposix_Posix
 * Method:    pread
 * Signature: (I[BIIJ)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_pread
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jlong);

/*
 * Class:     jposix_Posix
 * Method:    profil
 * Signature: ([SJI)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_profil
  (JNIEnv *, jclass, jshortArray, jlong, jint);

/*
 * Class:     jposix_Posix
 * Method:    pwrite
 * Signature: (I[BIIJ)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_pwrite
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint, jlong);

/*
 * Class:     jposix_Posix
 * Method:    read
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_read
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    readlink
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jposix_Posix_readlink
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    rmdir
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_rmdir
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    sbrk
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_jposix_Posix_sbrk
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jposix_Posix
 * Method:    setdomainname
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setdomainname
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    setegid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setegid
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    seteuid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_seteuid
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    setgid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setgid
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    setgroups
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setgroups
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     jposix_Posix
 * Method:    sethostid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_sethostid
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    sethostname
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_sethostname
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    setlogin
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setlogin
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    setpgid
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setpgid
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    setregid
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setregid
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    setresgid
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setresgid
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    setresuid
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setresuid
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    setreuid
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setreuid
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    setsid
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_setsid
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    setuid
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setuid
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    setusershell
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_setusershell
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    sleep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_sleep
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    stat
 * Signature: ([B)Ljposix/struct/Stat;
 */
JNIEXPORT jobject JNICALL Java_jposix_Posix_stat
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jposix_Posix_strerror
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    symlink
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_symlink
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_sync
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    sysconf
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_jposix_Posix_sysconf
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    tcgetpgrp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_tcgetpgrp
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    tcsetpgrp
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_tcsetpgrp
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    truncate
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_truncate
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     jposix_Posix
 * Method:    ttyname
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_jposix_Posix_ttyname
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    ttyslot
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_ttyslot
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    ualarm
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_ualarm
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    unlink
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_unlink
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     jposix_Posix
 * Method:    usleep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_jposix_Posix_usleep
  (JNIEnv *, jclass, jint);

/*
 * Class:     jposix_Posix
 * Method:    vfork
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_vfork
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    write
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix_write
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_DUPFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1DUPFD
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_DUPFD_CLOEXEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1DUPFD_1CLOEXEC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_GETFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1GETFD
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_SETFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1SETFD
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_GETFL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1GETFL
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_SETFL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1SETFL
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_GETLK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1GETLK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_SETLK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1SETLK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_SETLKW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1SETLKW
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_GETOWN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1GETOWN
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_SETOWN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1SETOWN
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_GETSIG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1GETSIG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_SETSIG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1SETSIG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_GETLEASE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1GETLEASE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_SETLEASE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1SETLEASE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_NOTIFY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1NOTIFY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_RDLCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1RDLCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_WRLCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1WRLCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_UNLCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1UNLCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_UNLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1UNLOCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_LOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1LOCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_TLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1TLOCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_TEST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1TEST
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_RDONLY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1RDONLY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_WRONLY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1WRONLY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_RDWR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1RDWR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_CREAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1CREAT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_EXCL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1EXCL
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_NOCTTY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1NOCTTY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_TRUNC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1TRUNC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_APPEND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1APPEND
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_NONBLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1NONBLOCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_NDELAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1NDELAY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_SYNC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1SYNC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_FSYNC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1FSYNC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_ASYNC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1ASYNC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_DIRECT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1DIRECT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_DIRECTORY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1DIRECTORY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_NOFOLLOW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1NOFOLLOW
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_DSYNC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1DSYNC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_RSYNC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1RSYNC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_O_LARGEFILE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1O_1LARGEFILE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_POSIX_FADV_NORMAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1POSIX_1FADV_1NORMAL
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_POSIX_FADV_SEQUENTIAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1POSIX_1FADV_1SEQUENTIAL
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_POSIX_FADV_RANDOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1POSIX_1FADV_1RANDOM
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_POSIX_FADV_NOREUSE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1POSIX_1FADV_1NOREUSE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_POSIX_FADV_WILLNEED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1POSIX_1FADV_1WILLNEED
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_POSIX_FADV_DONTNEED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1POSIX_1FADV_1DONTNEED
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IFMT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IFMT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IFDIR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IFDIR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IFCHR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IFCHR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IFREG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IFREG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IFIFO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IFIFO
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IFLNK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IFLNK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IFSOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IFSOCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_ISUID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1ISUID
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_ISGID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1ISGID
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IREAD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IREAD
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IWRITE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IWRITE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IEXEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IEXEC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IRUSR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IRUSR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IWUSR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IWUSR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IXUSR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IXUSR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IRWXU
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IRWXU
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IRGRP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IRGRP
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IWGRP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IWGRP
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IXGRP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IXGRP
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IRWXG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IRWXG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IROTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IROTH
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IWOTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IWOTH
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IXOTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IXOTH
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_S_IRWXO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1S_1IRWXO
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_R_OK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1R_1OK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_W_OK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1W_1OK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_X_OK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1X_1OK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_F_OK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1F_1OK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EPERM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EPERM
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOENT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOENT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ESRCH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ESRCH
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EINTR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EINTR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EIO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EIO
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENXIO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENXIO
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_E2BIG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1E2BIG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOEXEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOEXEC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EBADF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EBADF
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ECHILD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ECHILD
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EAGAIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EAGAIN
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOMEM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOMEM
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EACCES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EACCES
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EFAULT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EFAULT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOTBLK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOTBLK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EBUSY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EBUSY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EEXIST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EEXIST
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EXDEV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EXDEV
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENODEV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENODEV
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOTDIR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOTDIR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EISDIR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EISDIR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EINVAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EINVAL
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENFILE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENFILE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EMFILE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EMFILE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOTTY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOTTY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ETXTBSY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ETXTBSY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EFBIG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EFBIG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOSPC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOSPC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ESPIPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ESPIPE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EROFS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EROFS
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EMLINK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EMLINK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EPIPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EPIPE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EDOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EDOM
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ERANGE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ERANGE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EDEADLK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EDEADLK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENAMETOOLONG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENAMETOOLONG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOLCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOLCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOSYS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOSYS
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOTEMPTY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOTEMPTY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ELOOP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ELOOP
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EWOULDBLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EWOULDBLOCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOMSG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOMSG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EIDRM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EIDRM
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ECHRNG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ECHRNG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EL2NSYNC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EL2NSYNC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EL3HLT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EL3HLT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EL3RST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EL3RST
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ELNRNG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ELNRNG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EUNATCH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EUNATCH
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOCSI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOCSI
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EL2HLT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EL2HLT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EBADE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EBADE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EBADR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EBADR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EXFULL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EXFULL
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOANO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOANO
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EBADRQC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EBADRQC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EBADSLT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EBADSLT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EDEADLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EDEADLOCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EBFONT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EBFONT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOSTR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOSTR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENODATA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENODATA
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ETIME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ETIME
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOSR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOSR
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENONET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENONET
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOPKG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOPKG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EREMOTE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EREMOTE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOLINK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOLINK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EADV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EADV
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ESRMNT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ESRMNT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ECOMM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ECOMM
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EPROTO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EPROTO
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EMULTIHOP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EMULTIHOP
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EDOTDOT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EDOTDOT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EBADMSG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EBADMSG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EOVERFLOW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EOVERFLOW
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOTUNIQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOTUNIQ
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EBADFD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EBADFD
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EREMCHG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EREMCHG
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ELIBACC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ELIBACC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ELIBBAD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ELIBBAD
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ELIBSCN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ELIBSCN
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ELIBMAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ELIBMAX
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ELIBEXEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ELIBEXEC
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EILSEQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EILSEQ
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ERESTART
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ERESTART
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ESTRPIPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ESTRPIPE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EUSERS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EUSERS
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOTSOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOTSOCK
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EDESTADDRREQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EDESTADDRREQ
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EMSGSIZE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EMSGSIZE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EPROTOTYPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EPROTOTYPE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOPROTOOPT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOPROTOOPT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EPROTONOSUPPORT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EPROTONOSUPPORT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ESOCKTNOSUPPORT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ESOCKTNOSUPPORT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EOPNOTSUPP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EOPNOTSUPP
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EPFNOSUPPORT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EPFNOSUPPORT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EAFNOSUPPORT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EAFNOSUPPORT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EADDRINUSE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EADDRINUSE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EADDRNOTAVAIL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EADDRNOTAVAIL
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENETDOWN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENETDOWN
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENETUNREACH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENETUNREACH
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENETRESET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENETRESET
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ECONNABORTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ECONNABORTED
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ECONNRESET
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ECONNRESET
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOBUFS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOBUFS
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EISCONN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EISCONN
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOTCONN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOTCONN
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ESHUTDOWN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ESHUTDOWN
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ETOOMANYREFS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ETOOMANYREFS
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ETIMEDOUT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ETIMEDOUT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ECONNREFUSED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ECONNREFUSED
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EHOSTDOWN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EHOSTDOWN
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EHOSTUNREACH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EHOSTUNREACH
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EALREADY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EALREADY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EINPROGRESS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EINPROGRESS
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ESTALE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ESTALE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EUCLEAN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EUCLEAN
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOTNAM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOTNAM
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENAVAIL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENAVAIL
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EISNAM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EISNAM
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EREMOTEIO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EREMOTEIO
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EDQUOT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EDQUOT
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOMEDIUM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOMEDIUM
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EMEDIUMTYPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EMEDIUMTYPE
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ECANCELED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ECANCELED
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOKEY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOKEY
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EKEYEXPIRED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EKEYEXPIRED
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EKEYREVOKED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EKEYREVOKED
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EKEYREJECTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EKEYREJECTED
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_EOWNERDEAD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1EOWNERDEAD
  (JNIEnv *, jclass);

/*
 * Class:     jposix_Posix
 * Method:    _get_ENOTRECOVERABLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jposix_Posix__1get_1ENOTRECOVERABLE
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
